"use client";

import { useState } from "react";

const featuresTr = [
  { icon: "◌", title: "Gerçek piyasa verileri", text: "Piyasanın ritmini dışarıdan izlemek yerine, gerçek verilerle takip et." },
  { icon: "▣", title: "Sanal portföy", text: "100.000 USD sanal sermayeyle kararlarını gerçek para riski olmadan dene." },
  { icon: "↗", title: "Gerçekçi emir deneyimi", text: "Market ve limit emirleri, bekleyen emirler ve rezervasyon mantığı." },
  { icon: "≋", title: "Canlı piyasa derinliği", text: "Emir defterini ve gerçekleşen işlemleri tek bir akışta keşfet." },
  { icon: "◎", title: "Portföy ve performans", text: "Maliyet, gerçekleşmemiş kâr/zarar, dağılım ve işlem geçmişini anla." },
  { icon: "✦", title: "Öğrenerek ilerle", text: "Eğitim, ilerleme ve başarı sistemleri ürün vizyonunun bir parçası." },
];

const featuresEn = [
  { icon: "◌", title: "Real market data", text: "Follow the rhythm of the market through real external data." },
  { icon: "▣", title: "Virtual portfolio", text: "Test your decisions with $100,000 in virtual capital, without risking real money." },
  { icon: "↗", title: "Realistic order experience", text: "Market and limit orders, waiting orders and reservation logic." },
  { icon: "≋", title: "Live market depth", text: "Explore the order book and recent trades in one focused view." },
  { icon: "◎", title: "Portfolio and performance", text: "Understand cost basis, unrealized P/L, allocation and history." },
  { icon: "✦", title: "Learn as you progress", text: "Education, progression and achievements are part of the product vision." },
];

function LogoMark({ compact = false }: { compact?: boolean }) {
  return <span className={`logo-mark ${compact ? "logo-mark--compact" : ""}`} aria-hidden="true"><svg viewBox="0 0 32 32" role="presentation"><rect width="32" height="32" rx="7" className="logo-pilot-bg" /><path d="M6 23.5 15.8 6.5 26 23.5l-10-4.1Z" className="logo-pilot-mark" /><path d="M11 20.6h9.7" className="logo-pilot-cut" /><circle cx="15.9" cy="12.6" r="1.7" className="logo-pilot-dot" /></svg></span>;
}

function Brand({ compact = false }: { compact?: boolean }) {
  return <span className={compact ? "brand brand--compact" : "brand"}><LogoMark compact={compact} /><span>Borsa<span className="brand-pilot">Pilot</span></span></span>;
}

function TerminalMockup() {
  const candles: Array<[number, number, number, number, "up" | "down"]> = [
    [28, 103, 10, 30, "down"], [47, 95, 12, 36, "up"], [66, 108, 9, 28, "down"], [85, 82, 10, 43, "up"],
    [104, 76, 9, 34, "up"], [123, 89, 9, 38, "down"], [142, 70, 10, 49, "up"], [161, 62, 10, 42, "up"],
    [180, 74, 10, 30, "down"], [199, 51, 10, 53, "up"], [218, 42, 9, 52, "up"], [237, 58, 10, 37, "down"],
    [256, 37, 10, 56, "up"], [275, 45, 10, 43, "down"], [294, 31, 10, 55, "up"], [313, 24, 10, 55, "up"],
    [332, 38, 10, 43, "down"], [351, 29, 10, 49, "up"],
  ];
  return (
    <div className="terminal-shell" aria-label="BorsaPilot terminal önizlemesi, görsel amaçlı örnek veriler içerir">
      <div className="terminal-topbar"><div className="traffic"><b /><b /><b /></div><span className="terminal-title">BORSAPILOT <em>/</em> TERMİNAL</span><div className="terminal-markets"><span className="active">KRİPTO</span><span>BIST</span><span>ABD</span></div><span className="terminal-status"><span /> ÖRNEK GÖRÜNÜM</span></div>
      <div className="terminal-body">
        <aside className="terminal-sidebar"><div className="side-label">PİYASA</div>{["BTC / USDT", "ETH / USDT", "SOL / USDT", "BNB / USDT"].map((x, i) => <div className={`watch-row ${i === 0 ? "selected" : ""}`} key={x}><span className="coin-dot">{x[0]}</span><span>{x}</span><strong>{["104,286", "3,842", "182.4", "671.2"][i]}</strong><small className={i === 1 ? "red" : "green"}>{i === 1 ? "−1.24%" : `+${["2.84", "", "4.18", "1.06"][i]}%`}</small></div>)}<div className="side-label side-label--bottom">İZLEME LİSTESİ</div><div className="watch-row faded"><span className="coin-dot">A</span><span>AVAX / USDT</span><strong>38.62</strong></div><div className="watch-row faded"><span className="coin-dot">X</span><span>XRP / USDT</span><strong>2.41</strong></div></aside>
        <main className="terminal-chart"><div className="chart-head"><div><span className="pair-name">BTC / USDT</span><span className="pair-change">+2.84%</span><span className="sample-pill">ÖRNEK VERİ</span></div><div className="timeframes"><span>1S</span><span>4S</span><span className="active">1G</span><span>1H</span></div></div><div className="chart-area"><div className="chart-grid" />{candles.map(([x, y, w, h, dir]) => <span key={x} className={`candle ${dir}`} style={{ left: `${x / 3.8}%`, top: `${y / 1.48}%`, height: `${h / 1.2}px` }} />)}<svg className="chart-line" viewBox="0 0 380 180" preserveAspectRatio="none" aria-hidden="true"><path d="M2 147 C28 131,35 150,56 128 S83 143,103 96 S129 111,150 78 S173 89,190 66 S216 76,233 58 S260 75,280 39 S305 62,325 28 S351 49,378 12" /></svg><div className="price-tag">104,286</div><div className="x-labels"><span>08:00</span><span>12:00</span><span>16:00</span><span>20:00</span></div></div></main>
        <aside className="terminal-order"><div className="order-tabs"><span className="active">EMİR DEFTERİ</span><span>İŞLEMLER</span></div><div className="depth-head"><span>FİYAT (USDT)</span><span>MİKTAR (BTC)</span></div><div className="depth-list asks">{[["104,412", "0.84"], ["104,365", "1.20"], ["104,318", "0.32"], ["104,301", "0.56"]].map(([a,b]) => <div key={a}><i /><span>{a}</span><b>{b}</b></div>)}</div><div className="last-price">104,286 <small>≈ $104,286</small></div><div className="depth-list bids">{[["104,244", "1.06"], ["104,198", "0.42"], ["104,120", "0.78"], ["104,086", "1.34"]].map(([a,b]) => <div key={a}><i /><span>{a}</span><b>{b}</b></div>)}</div><div className="order-actions"><div className="order-action-tabs"><span className="active">ALIŞ</span><span>SATIŞ</span></div><div className="order-fields"><div><small>Fiyat</small><b>104,286</b></div><div><small>Miktar</small><b>0.00 BTC</b></div></div><div className="order-buttons"><span className="buy">AL</span><span className="sell">SAT</span></div></div><div className="order-summary"><div><small>Sanal bakiye</small><strong>$100,000.00</strong></div><div><small>Portföy değeri</small><strong>$100,000.00</strong></div></div></aside>
      </div>
      <div className="terminal-footer"><span><i /> Bağlantı beklemede</span><span>Görsel amaçlı arayüz önizlemesi</span><span>USD <b>⌄</b></span></div>
    </div>
  );
}

function RealTerminalMockup({ language }: { language: "tr" | "en" }) {
  const isEnglish = language === "en";
  const candles = [
    [5, 66, 7, 26, "down"], [10, 59, 7, 38, "up"], [15, 74, 7, 25, "down"], [20, 53, 7, 43, "up"],
    [25, 61, 7, 34, "down"], [30, 43, 7, 47, "up"], [35, 51, 7, 37, "up"], [40, 34, 7, 48, "up"],
    [45, 41, 7, 38, "down"], [50, 27, 7, 47, "up"], [55, 35, 7, 43, "up"], [60, 22, 7, 49, "down"],
    [65, 30, 7, 39, "up"], [70, 17, 7, 52, "up"], [75, 25, 7, 43, "down"], [80, 13, 7, 53, "up"],
    [85, 20, 7, 43, "up"], [90, 9, 7, 52, "down"],
  ] as Array<[number, number, number, number, "up" | "down"]>;
  return (
    <div className="product-terminal" aria-label="BorsaPilot terminal yapısına dayalı görsel önizleme; örnek veriler içerir">
      <div className="product-header"><div className="product-brand"><LogoMark compact /><b>BORSAPILOT</b><span>Terminal</span></div><div className="market-switch"><span>{isEnglish ? "Domestic" : "Yurt İçi"}</span><span>{isEnglish ? "International" : "Yurt Dışı"}</span><span className="active">{isEnglish ? "Crypto" : "Kripto"}</span></div><div className="quote-strip"><div><b>BTC/USDT</b><small>104,286</small></div><div><b>ETH/USDT</b><small>3,842</small></div><div><b>SOL/USDT</b><small>182.4</small></div><div className="clock"><b>{isEnglish ? "TIME" : "SAAT"}</b><small>22:47:40</small></div></div></div>
      <div className="instrument-bar"><span className="search-icon">⌕</span><b>BTC/USDT</b><span className="instrument-kind">CRYPTO</span><small>{isEnglish ? "Click to select an instrument" : "Enstrüman seçmek için tıklayın"}</small><span className="star">☆</span><div className="instrument-metric"><small>{isEnglish ? "PRICE" : "FİYAT"}</small><b>104,286</b></div><div className="instrument-metric"><small>{isEnglish ? "CHANGE" : "DEĞİŞİM"}</small><b className="green">+2.84%</b></div></div>
      <div className="product-grid">
        <aside className="workspace-watchlist"><div className="workspace-tabs"><span className="active">{isEnglish ? "Watchlist" : "İzleme Listesi"}</span><span>{isEnglish ? "Recent instruments" : "Son Enstrümanlar"}</span><span>{isEnglish ? "Waiting orders" : "Bekleyen Emirler"}</span></div><div className="watchlist-switch"><span>←</span><b>Crypto⌄</b><span>→</span></div><div className="watchlist-actions"><span>{isEnglish ? "RENAME" : "YENİDEN ADLANDIR"}</span><span>{isEnglish ? "NEW" : "YENİ"}</span><span>{isEnglish ? "DELETE" : "SİL"}</span></div><div className="watchlist-empty">{isEnglish ? "Your watchlist is empty" : "İzleme listeniz boş"}</div></aside>
        <div className="product-center"><div className="product-chart"><div className="chart-toolbar"><b>BTC/USDT</b><span>15m</span><span>1h</span><span>4h</span><span className="active">1D</span><span>1W</span><span>1M</span></div><div className="product-chart-stage"><div className="chart-grid" />{candles.map(([x, y, w, h, dir]) => <span key={x} className={`candle ${dir}`} style={{ left: `${x}%`, top: `${y}%`, height: `${h}px`, width: `${w}px` }} />)}<svg className="chart-line" viewBox="0 0 380 150" preserveAspectRatio="none" aria-hidden="true"><path d="M2 125 C25 108,36 125,54 107 S80 119,97 88 S124 104,142 72 S168 84,187 65 S210 74,232 51 S255 68,276 41 S301 57,321 27 S350 42,378 10" /></svg><span className="chart-watermark">{isEnglish ? "SAMPLE CHART DATA" : "ÖRNEK GRAFİK VERİSİ"}</span></div></div><div className="order-entry"><div className="order-entry-head"><div><small>{isEnglish ? "ORDER ENTRY" : "EMİR GİRİŞİ"}</small><b>BTC/USDT</b></div><span className="active">{isEnglish ? "LIMIT ORDER" : "LİMİT EMİR"}</span><span>{isEnglish ? "MARKET ORDER" : "PİYASA EMRİ"}</span></div><div className="order-columns"><div className="buy-column"><small>{isEnglish ? "AVAILABLE USDT" : "KULLANILABİLİR USDT"}</small><b>100.000,00 <em>USDT</em></b><label>{isEnglish ? "PRICE" : "FİYAT"}</label><span>0,00</span><label>{isEnglish ? "AMOUNT" : "MİKTAR"}</label><span>0,00</span><label>{isEnglish ? "TOTAL" : "TOPLAM"}</label><span>0,00 USDT</span><div className="percent-row"><i>25%</i><i>50%</i><i>75%</i><i>100%</i></div><strong>{isEnglish ? "Buy BTC" : "BTC Al"}</strong></div><div className="sell-column"><small>{isEnglish ? "AVAILABLE BTC" : "KULLANILABİLİR BTC"}</small><b>0,75 <em>BTC</em></b><label>{isEnglish ? "PRICE" : "FİYAT"}</label><span>0,00</span><label>{isEnglish ? "AMOUNT" : "MİKTAR"}</label><span>0,00</span><label>{isEnglish ? "TOTAL" : "TOPLAM"}</label><span>0,00 USDT</span><div className="percent-row"><i>25%</i><i>50%</i><i>75%</i><i>100%</i></div><strong>{isEnglish ? "Sell BTC" : "BTC Sat"}</strong></div></div></div></div>
        <aside className="workspace-right"><div className="depth-card"><div className="right-tabs"><span className="active">{isEnglish ? "Depth" : "Derinlik"}</span><span>{isEnglish ? "Recent trades" : "Piyasa İşlemleri"}</span></div><div className="depth-columns"><small>{isEnglish ? "PRICE" : "FİYAT"}</small><small>{isEnglish ? "AMOUNT" : "MİKTAR"}</small></div><div className="depth-message">{isEnglish ? "Order book is syncing" : "Emir defteri senkronize ediliyor"}</div><div className="depth-balance"><span>{isEnglish ? "SPREAD" : "MAKAS"}<br /><b>--</b></span><span>{isEnglish ? "NET BALANCE" : "NET DENGE"}<br /><b className="green">+0,00</b></span></div><div className="depth-message">{isEnglish ? "Order book is syncing" : "Emir defteri senkronize ediliyor"}</div><button>{isEnglish ? "VIEW DEPTH" : "DERİNLİĞİ GÖR"}</button></div><div className="feed-card"><div className="feed-title">{isEnglish ? "AI NEWS / MARKET FLOW" : "AI HABER / PİYASA AKIŞI"}<small>{isEnglish ? "Future market news and insight area" : "Gelecek piyasa haberleri ve içgörü alanı"}</small></div><div><b>{isEnglish ? "AI NEWS" : "AI HABER"} <small>{isEnglish ? "FUTURE" : "GELECEK"}</small></b><p>{isEnglish ? "Future AI market news and insight flows will appear here." : "Gelecek AI piyasa haberleri ve içgörü akışları burada yer alacak."}</p></div><div><b>{isEnglish ? "MARKET BRIEF" : "PİYASA ÖZETİ"} <small>{isEnglish ? "PLANNED" : "PLANLANDI"}</small></b><p>{isEnglish ? "A planned space for live market context." : "Canlı piyasa bağlamı için planlanan alan."}</p></div><div><b className="yellow">{isEnglish ? "INSIGHTS" : "İÇGÖRÜLER"} <small>{isEnglish ? "LATER" : "SONRA"}</small></b><p>{isEnglish ? "AI-assisted summaries can be added in a later phase." : "AI destekli özetler sonraki fazda eklenebilir."}</p></div></div></aside>
      </div>
    </div>
  );
}

export default function Home() {
  const [language, setLanguage] = useState<"tr" | "en">("tr");
  const isEnglish = language === "en";
  const features = isEnglish ? featuresEn : featuresTr;
  const copy = isEnglish ? {
    soon: "Coming soon", eyebrow: "LEARN BY EXPERIENCING THE MARKET", heroTitle: <>Learn markets <span>by doing.</span></>, heroText: "Practice with real market data. Test your strategies with virtual capital and learn by experiencing markets without risking real money.", firstVersion: "First release: crypto markets", valueKicker: "WHY BORSAPILOT?", valueTitle: <>More than watching markets.<br /><em>Experience them.</em></>, valueText: "BorsaPilot is a simulation and learning platform designed to help you understand market behavior through practice. Follow real data and test your decisions with virtual capital.", loopTitle: "LEARNING LOOP", loopOne: "Observe", loopOneSub: "Read the market", loopTwo: "Decide", loopTwoSub: "Use virtual capital", loopThree: "Analyze", loopThreeSub: "See what happened", loopSignal: "SIMULATION SIGNAL", loopInsight: "Experience → Insight", loopLearning: "+ learning", featureKicker: "THE FOUNDATION", featureTitle: <>More than a terminal.<br /><em>A place to learn.</em></>, featureIntro: "Better decisions start with observing the market — and your own behavior.", processKicker: "THE LEARNING LOOP", processTitle: <>Make a decision.<br /><em>See the result.</em></>, processText: "BorsaPilot turns understanding the market from passive watching into an active practice.", steps: [["Observe the market", "Start reading price, depth and movement."], ["Decide with virtual capital", "Test your strategy against real market flow."], ["Analyze the result", "Review your portfolio and see what you learned."]], visionKicker: "PRODUCT VISION", visionTitle: <>The first step<br /><em>is the beginning.</em></>, visionText: "Starting with crypto markets today, BorsaPilot aims to bring together more markets and deeper learning tools over time.", now: "NOW", nowTitle: "Crypto markets", nowSub: "First simulation experience", later: "NEXT", laterTitle: "BIST & global markets", laterSub: "New asset classes", vision: "VISION", visionNodeTitle: "Financial learning", visionSub: "Analysis, progression and discovery", finalKicker: "THE JOURNEY BEGINS", finalTitle: <>BorsaPilot<br /><em>is taking shape.</em></>, finalText: <>We are working on the first release.<br />A new way to learn markets is coming soon.</>, disclaimer: <>BorsaPilot is a market simulation and financial learning product.<br />It does not execute real investments.</>, company: "A TunoDijital product."
  } : {
    soon: "Çok yakında", eyebrow: "PİYASAYI DENEYİMLEYEREK ÖĞREN", heroTitle: <>Piyasayı deneyerek<br /><span>öğren.</span></>, heroText: "Gerçek piyasa verileriyle işlem pratiği yap. Sanal sermayenle stratejilerini test et, piyasaları risk almadan deneyimleyerek öğren.", firstVersion: "İlk sürüm: kripto piyasaları", valueKicker: "NEDEN BORSAPİLOT?", valueTitle: <>Piyasayı izlemek yetmez.<br /><em>Deneyimlemek gerekir.</em></>, valueText: "BorsaPilot, piyasa davranışlarını yaşayarak öğrenmen için tasarlanmış bir simülasyon ve öğrenme platformu. Gerçek verileri takip ederken kararlarını sanal sermayeyle dene.", loopTitle: "ÖĞRENME DÖNGÜSÜ", loopOne: "Gözlemle", loopOneSub: "Piyasayı oku", loopTwo: "Karar ver", loopTwoSub: "Sanal sermayeyi kullan", loopThree: "Analiz et", loopThreeSub: "Sonucunu gör", loopSignal: "SİMÜLASYON SİNYALİ", loopInsight: "Deneyim → İçgörü", loopLearning: "+ öğrenme", featureKicker: "PLATFORMUN TEMELİ", featureTitle: <>Bir terminalden fazlası.<br /><em>Bir öğrenme alanı.</em></>, featureIntro: "İyi kararlar, piyasayı ve kendi davranışını gözlemlemekle başlar.", processKicker: "ÖĞRENME DÖNGÜSÜ", processTitle: <>Karar ver.<br /><em>Sonucunu gör.</em></>, processText: "BorsaPilot, piyasayı anlamayı bir izleme alışkanlığından çıkarıp pratik bir sürece dönüştürür.", steps: [["Piyasayı takip et", "Fiyatı, derinliği ve hareketi okumaya başla."], ["Sanal sermayeyle karar ver", "Stratejini gerçek piyasa akışı üzerinde dene."], ["Sonuçlarını analiz et", "Portföyünü incele, ne öğrendiğini fark et."]], visionKicker: "ÜRÜN VİZYONU", visionTitle: <>İlk adım<br /><em>başlangıçtır.</em></>, visionText: "Bugün kripto piyasalarıyla başlayan BorsaPilot, zamanla farklı piyasaları ve daha derin öğrenme araçlarını bir araya getirmeyi hedefliyor.", now: "ŞİMDİ", nowTitle: "Kripto piyasaları", nowSub: "İlk simülasyon deneyimi", later: "SONRA", laterTitle: "BIST & global piyasalar", laterSub: "Yeni varlık sınıfları", vision: "VİZYON", visionNodeTitle: "Finansal öğrenme", visionSub: "Analiz, ilerleme ve keşif", finalKicker: "YOLCULUK BAŞLIYOR", finalTitle: <>BorsaPilot<br /><em>hazırlanıyor.</em></>, finalText: <>İlk sürüm üzerinde çalışıyoruz.<br />Piyasaları deneyerek öğrenmek için çok yakında buradayız.</>, disclaimer: <>BorsaPilot bir yatırım simülasyonu ve eğitim ürünüdür.<br />Gerçek yatırım işlemi gerçekleştirmez.</>, company: "Bir TunoDijital ürünüdür."
  };

  return <main>
    <nav className="nav container"><a href="#top" aria-label="BorsaPilot ana sayfa"><Brand /></a><div className="nav-right"><button type="button" className="language-switch" onClick={() => setLanguage(isEnglish ? "tr" : "en")} aria-label={isEnglish ? "Türkçeye geç" : "Switch to English"}><span className={!isEnglish ? "active" : ""}>TR</span><i>/</i><span className={isEnglish ? "active" : ""}>EN</span></button><span className="nav-dot" /> <span>{copy.soon}</span></div></nav>
    <section className="hero container" id="top"><div className="hero-copy"><div className="eyebrow"><span /> {copy.eyebrow}</div><h1>{copy.heroTitle}</h1><p>{copy.heroText}</p><div className="hero-meta"><div className="coming-badge"><span className="pulse" /> {copy.soon}</div><span className="meta-separator" /><span>{copy.firstVersion}</span></div></div><div className="hero-terminal"><div className="terminal-glow" /><RealTerminalMockup language={language} /></div></section>
    <section className="value-section"><div className="container value-grid"><div className="section-kicker">01 <span /> {copy.valueKicker}</div><div><h2>{copy.valueTitle}</h2><p>{copy.valueText}</p></div><div className="learning-visual" aria-label="BorsaPilot learning loop"><div className="learning-visual-head"><span>{copy.loopTitle}</span><b>01 — 03</b></div><div className="learning-track"><div className="learning-node active"><i>01</i><b>{copy.loopOne}</b><small>{copy.loopOneSub}</small></div><span className="learning-connector" /><div className="learning-node"><i>02</i><b>{copy.loopTwo}</b><small>{copy.loopTwoSub}</small></div><span className="learning-connector" /><div className="learning-node"><i>03</i><b>{copy.loopThree}</b><small>{copy.loopThreeSub}</small></div></div><div className="learning-signal"><span>{copy.loopSignal}</span><b>{copy.loopInsight}</b><em>{copy.loopLearning}</em></div></div></div></section>
    <section className="features container"><div className="section-intro"><div className="section-kicker">02 <span /> {copy.featureKicker}</div><h2>{copy.featureTitle}</h2><p>{copy.featureIntro}</p></div><div className="feature-grid">{features.map((feature, i) => <article className="feature-card" key={feature.title}><div className="feature-top"><span className="feature-number">0{i + 1}</span><span className="feature-icon">{feature.icon}</span></div><h3>{feature.title}</h3><p>{feature.text}</p><span className="card-line" /></article>)}</div></section>
    <section className="process-section"><div className="container"><div className="process-head"><div><div className="section-kicker">03 <span /> {copy.processKicker}</div><h2>{copy.processTitle}</h2></div><p>{copy.processText}</p></div><div className="steps">{copy.steps.map(([title, text], i) => <div className="step" key={title}><span>0{i + 1}</span><div><h3>{title}</h3><p>{text}</p></div></div>)}</div></div></section>
    <section className="vision container"><div className="vision-copy"><div className="section-kicker">04 <span /> {copy.visionKicker}</div><h2>{copy.visionTitle}</h2><p>{copy.visionText}</p></div><div className="vision-map"><div className="map-line" /><div className="vision-node now"><span>{copy.now}</span><b>{copy.nowTitle}</b><small>{copy.nowSub}</small></div><div className="vision-node future f1"><span>{copy.later}</span><b>{copy.laterTitle}</b><small>{copy.laterSub}</small></div><div className="vision-node future f2"><span>{copy.vision}</span><b>{copy.visionNodeTitle}</b><small>{copy.visionSub}</small></div></div></section>
    <section className="final-cta"><div className="container"><div className="final-orbit" /><div className="section-kicker">05 <span /> {copy.finalKicker}</div><h2>{copy.finalTitle}</h2><p>{copy.finalText}</p><div className="final-status"><span className="pulse" /> {copy.soon}</div></div></section>
    <footer className="footer container"><Brand compact /><div className="footer-right"><p>{copy.disclaimer}</p><span>© 2026 BorsaPilot · {copy.company}</span></div></footer>
  </main>;
}
